- name: Ajouter une clé ssh
  hosts: 192.168.100.161
  become: yes

  vars:
    username: "{{ username }}"          # demandé dans AWX
    ssh_key: "{{ ssh_key }}"            # demandé dans AWX
    key_type: "{{ key_type }}"          # demandé dans AWX (ssh-rsa, ssh-ed25519…)
    key_comment: "{{ key_comment }}"    # demandé dans AWX

    # Construction automatique de la clé finale
    my_public_key: "{{ key_type }} {{ ssh_key | regex_replace('\\s+', '') }} {{ key_comment }}"

  tasks:
    - name: Créer l'utilisateur s'il n'existe pas
      user:
        name: "{{ username }}"
        shell: /bin/bash
        create_home: yes
        state: present

    # 🔒 home appartient username
    - name: home appartient username
      file:
        path: "/home/{{ username }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        #mode: '0755'

    - name: Créer le dossier .ssh si absent
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'
        force: yes

    - name: Ajouter la clé publique dans authorized_keys
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ my_public_key }}"

    # 🔒 Sécurisation du dossier .ssh
    - name: Mettre root propriétaire du dossier .ssh
      file:
        path: "/home/{{ username }}/.ssh"
        owner: root
        group: root
        mode: '0755'

    # 🔒 Sécurisation du fichier authorized_keys
    - name: Mettre root propriétaire du fichier authorized_keys
      file:
        path: "/home/{{ username }}/.ssh/authorized_keys"
        owner: root
        group: root
        mode: '0644'
