- name: Supprimer une clé SSH
  hosts: 192.168.100.161
  become: yes

  vars:
    username: "{{ username }}"
    cle_a_supprimer: "{{ cle_a_supprimer }}"

  tasks:
    - name: Supprimer la clé publique dans authorized_keys
      authorized_key:
        user: "{{ username }}"
        state: absent
        key: "{{ cle_a_supprimer }}"
        path: "/home/{{ username }}/.ssh/authorized_keys"

    # 🔒 Resécuriser le dossier .ssh
    - name: Mettre root propriétaire du dossier .ssh
      file:
        path: "/home/{{ username }}/.ssh"
        owner: root
        group: root
        mode: '0755'

    # 🔒 Resécuriser le fichier authorized_keys
    - name: Mettre root propriétaire du fichier authorized_keys
      file:
        path: "/home/{{ username }}/.ssh/authorized_keys"
        owner: root
        group: root
        mode: '0644'
