- name: Mise à jour automatique des machines
  hosts: clients
  become: yes
  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer les mises à jour
      apt:
        upgrade: dist
