---
- name: Test formatage ss + awk
  hosts: goupe_teste_clients
  gather_facts: no
  become: yes

  tasks:

    - name: Exécuter ss + awk formaté
      command: >
        bash -c "ss -tulpan | awk 'NR==1 {print \"PROTO | STATE | LOCAL_IP:PORT | REMOTE_IP:PORT | PROCESS\"; print \"--------------------------------------------------------------------------------\"} NR>1 {printf \"%-8s | %-12s | %-25s | %-25s | %s\n\", $1, $2, $5, $6, $7}'"
      register: ss_formatted

    - name: Sauvegarder le résultat dans /tmp/ss_test.txt
      copy:
        dest: /tmp/ss_test.txt
        mode: '0644'
        content: |
          === TEST FORMATAGE SS + AWK ===

          {{ ss_formatted.stdout }}
